name: Deploy on Production Environment
run-name: "${{ github.actor }} is deploying on production environment ðŸš€"
on:
  push:
    branches:
      - main

jobs:
  deploy-theme:
    name: "Deploy on production server"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload files to FTP
        uses: matteodf/lftp-upload@v1.1.0
        with:
            host: ${{ secrets.FTP_HOST_PROD }}
            username: ${{ secrets.FTP_USERNAME_PROD }}
            password: ${{ secrets.FTP_PASSWORD_PROD }}
            forceSsl: "true"
            localDir: .
            remoteDir: www/adhesion
