name: Deploy on Staging Environment
run-name: "${{ github.actor }} is deploying on staging environment ðŸš§"
on:
  push:
    branches:
      - develop

jobs:
  deploy-theme:
    name: "Deploy on staging server"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MR_ROBOT_SSH_KEY }}

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MR_ROBOT_SSH_KEY }}
          known_hosts: unnecessary

      - name: "Adding Known Hosts"
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: "Deploy to remote server"
        run: |
          source .github/.env.ci
          rsync -avzP -e 'ssh' --exclude='.github' --exclude='.git' . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:applications/$APP_SYS_USR/public_html/adhesion
